### PR TITLE
add license

### PR DESCRIPTION
**Pull request by soenkehahn**
Are you all ok with publishing your contributions under CC BY 4.0 as done by this PR?
(http://creativecommons.org/licenses/by/4.0/)

The reason for this request is #50.

If yes, it would be great if everyone could give their approval in this thread. Thanks a lot!

CC: 
- [x] @alpmestan 
- [x] @jkarni 
- [x] @ggreif 
- [x] @yamadapc 
- [x] @jsl 
- [x] @zudov 
- [x] @joncfoo 
- [x] @johntyree 
- [x] @fisx 
- [x] @dmjio 
- [x] @Chobbes 
- [x] @fizruk 
- [x] @mgeisler 
- [x] @jhedev 
- [x] @FranklinChen 
- [x] @arianvp 
- [x] @hrldcpr 
- [x] @dredozubov

### CODE REVIEW

**Comment by jhedev** [comment]
I'm ok with it :+1:

**Comment by alpmestan** [comment]
:+1: from me

**Comment by mgeisler** [comment]
Sure!

**Comment by jsl** [comment]
Fine by me.

**Comment by arianvp** [comment]
Im fine with it

**Comment by dredozubov** [comment]
sure!

**Comment by joncfoo** [comment]
All good

**Comment by Chobbes** [comment]
Do it! Free the servant!

**Comment by joncfoo** [comment]
Just remembered that CC doesn't recommend using their license for code:  https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

[ISC](https://opensource.org/licenses/ISC), [MIT](https://opensource.org/licenses/MIT), or [2-clause BSD](https://opensource.org/licenses/BSD-2-Clause) license might work better.

**Comment by joncfoo** [comment]
Sorry, I haven't had my coffee yet - this is for the docs correct?  If so, please ignore =\

**Comment by johntyree** [comment]
:+1:

**Comment by soenkehahn** [comment]
@joncfoo: Yes, just for this repo.

**Comment by alpmestan** [comment]
@soenkehahn well i guess the license must apply to `doc/tutorial` in the servant repo as well

**Comment by FranklinChen** [comment]
Yes.

**Comment by hrldcpr** [comment]
Yup.

**Comment by fizruk** [comment]
:+1:

**Comment by zudov** [comment]
:+1:

**Comment by arianvp** [comment]
We just need @jkarni @ggreif @jsl @dmjio @fisx 's OK and then we can merge

**Comment by jkarni** [comment]
OK from me.

**Comment by fisx** [comment]
I'm ok with publishing your contributions under CC BY 4.0 as done by this PR.

**Comment by ggreif** [comment]
I'm ok with publishing your contributions under CC BY 4.0 as done by this PR.

**Comment by dmjio** [comment]
:+1:

**Comment by soenkehahn** [comment]
And @yamadapc is still missing.

**Comment by yamadapc** [comment]
All good!

**Comment by arianvp** [comment]
LGTM.

@soenkehahn I'm not sure why travis is failing

**Comment by soenkehahn** [comment]
@arianvp: Unfortunately CI is broken for this repo currently.

I'll merge...

**Comment by soenkehahn** [comment]
Merged and published.

**Pull request merged**
