### PR TITLE
Add link to consultancies.

### PR DESCRIPTION
**Pull request by jkarni**

### CODE REVIEW

**Comment by arianvp** [comment]
I feel semi-okayish to this.  I prefer just having companies in the `CONTRIBUTORS` file instead.   If there's a clear wayfor people to get on this list then it's okay.

**Comment by soenkehahn** [comment]
LGTM.

@arianvp: I think, the consultancies list should be distinct from the contributors list. Someone can of course offer to work as a consultant without having contributed and vice versa. Of course, there's some overlap.

The way to get on this list is to create a PR, as stated in the comment above the list. @arianvp: How can we make this clearer?

**Comment by arianvp** [comment]
@soenkehahn I somehow missed that line.

**Comment by alpmestan** [comment]
LGTM. I'll probably add myself there soonish =)

**Comment by jkarni** [comment]
Not sure what the build failures are about...

**Comment by soenkehahn** [comment]
@jkarni: CI in this repo is broken, unfortunately. Feel free to merge. Or fix the CI. :(

**Pull request merged**
