### PR TITLE
Improve rendering on small displays

### PR DESCRIPTION
**Pull request by yamadapc**
Improves how the website looks on small displays and mobile.

### CODE REVIEW

**Comment by soenkehahn** [comment]
@yamadapc: What exactly does this change? I don't see the difference. (And I'm very bad with css...)

**Comment by soenkehahn** [comment]
(`travis` failed due to some unrelated link check error. I've restarted the build.)

**Comment by yamadapc** [comment]
So; with a hard-set `width: 900px`, when the screen is smaller than `900px`, a scroll-bar will appear, keeping the body width at `900px`.

Usually you don't want this unless you're explicitly not supporting small displays. `max-width` makes it so that if the screen is bigger than `900px` the body will be kept at `900px` at max, but if it's smaller, it'll be resized to be as big as it can be.

I've added a small amount of padding so it wouldn't touch the window frame borders. Honestly I didn't open it on a mobile device (just the inspectors device view) so I don't know if `20px` is the perfect spacing between the screen edge and the content, but this makes the website readable on small displays.

If you're online right now, hit http://932aabbe.ngrok.io/ and resize the window to see the changes live.

**Comment by yamadapc** [comment]
Well... Okay; I've just opened that on a mobile device, seems I just fixed small displays on a desktop computer. Give me a moment to make it look good on mobile.

**Comment by yamadapc** [comment]
Cool, there was a missing `meta` tag which caused the website to be downscalled on mobile. This last commit adds it and makes a couple of changes which make headings and the menu render properly. You can read about the meta tag thing here: https://developers.google.com/speed/docs/insights/ConfigureViewport. I'll keep that ngrok tunnel while I'm up today (so a couple more hours).

Open it on mobile! http://932aabbe.ngrok.io/

**Comment by yamadapc** [comment]
Fixed one more minor issue with the inlined `code` tags overflowing and causing the viewport to expand to the right.

**Comment by soenkehahn** [comment]
Very nice work, thanks a lot. Will merge and deploy soonish. (If no one else beats me to it.)

**Comment by soenkehahn** [comment]
Unless you want to add more commits. Do you?

**Comment by yamadapc** [comment]
This is an improvement as it is. Going through the tuturial there're still a couple of things that look bad on mobile like the `blockquote`s and the justified lists.

Feel free to merge and I'll open another one if I fix them.

It'd be cool to take that pretty logo of yours and build a website that went more in that visual direction... I don't know if you've any plans in that sense.

**Comment by soenkehahn** [comment]
Merged and deployed. Thanks again!

Regarding further fixes: @fizruk was planning to move the tutorial into the main `servant` repo and move to http://readthedocs.org. I'm guessing that we can (and want) to use our own css there too. But I'm not sure how exactly that would be done. See https://github.com/haskell-servant/servant/issues/338. Apart from that some more work on the looks of the tutorial would be very much appreciated.

Regarding the logo: there has been some discussion to have a new logo: https://groups.google.com/d/topic/haskell-servant/fHnTn3LWeUc/discussion. So I don't know how long the current logo will stick around. (Also pinging @fizruk.)

**Comment by yamadapc** [comment]
Cool. Sent you an e-mail with a git patch for the other fixes ([this patch](https://gist.github.com/anonymous/8f1cec2e4949c3a0d457)). Didn't want to trigger another notification.

Personally, I feel like having a website (even if it's just a LP) is good marketing. JS people tend to do this pretty well:
- http://expressjs.com/
- http://hapijs.com/
- http://loopback.io/
- https://mochajs.org/

Of course JS doesn't have haddock so everyone ends up building themes for JSDoc or custom documentation pages.

I also think that readthedocs is ugly, but that's completely subjective. A Haskell example of a pretty homepage, is `hspec`'s website:
- http://hspec.github.io/

It's nice to have a clean overview of what we're buying; you do have a blog and I understand #338 is only about porting the tutorials. Will be alert for if/when a new logo appears.

**Comment by soenkehahn** [comment]
(I don't mind the github notifications.)

Regarding styling/good marketing: I completely agree. The more polished the site looks the better. Especially if it's a site for a web-framework.

And yes, you're right, #338 is only about the tutorial, so styling this repo here still makes sense. (I'll apply your patch tomorrow.)

Regarding readthedocs: I think we should try to use our own css and then the ugliness of the default css doesn't matter.

**Pull request merged**
